#!/usr/bin/env node
// Generates the multi-language HTML for interactive posts. Zero dependencies —
// run it with `node build.mjs` from the blog root.
//
// A post opts in by having a `src/` folder containing:
//   content.html   structure + copy, written in the source language
//   shell.html     page chrome, with {{lang}} {{title}} {{description}}
//                  {{alternates}} {{content}} placeholders
//   <lang>.mjs     one module per language (see src/ko.mjs, src/en.mjs)
//
// Exactly one language module sets `source: true`; its page is content.html
// verbatim. Every other module supplies an overlay of translated copy, which
// this script applies to the same markup so the two pages can never drift
// structurally. Equations and demo markup are never duplicated across languages.

import { readFile, writeFile, readdir } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = path.dirname(fileURLToPath(import.meta.url));
const BANNER = 'GENERATED by build.mjs from src/ — edit the sources, not this file.';

const problems = [];
const fail = (msg) => problems.push(msg);

/* ---------------------------------------------------------------- html utils */

const escapeHtml = (s) =>
  s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

// Locates the first element whose opening tag matches `openRe`, starting at
// `from`. The target elements in content.html never nest inside themselves, so
// a scan to the first matching close tag is exact — and asserted below.
function locate(html, openRe, tag, from = 0) {
  const re = new RegExp(openRe.source, openRe.flags.replace('g', '') + 'g');
  re.lastIndex = from;
  const open = re.exec(html);
  if (!open) return null;
  const innerStart = open.index + open[0].length;
  const innerEnd = html.indexOf(`</${tag}>`, innerStart);
  if (innerEnd === -1) throw new Error(`unclosed <${tag}> at ${open.index}`);
  const inner = html.slice(innerStart, innerEnd);
  if (new RegExp(`<${tag}[\\s>]`).test(inner)) {
    throw new Error(`<${tag}> nests inside itself near offset ${open.index}; ` +
      'the flat-scan assumption in build.mjs no longer holds');
  }
  return { start: open.index, innerStart, inner, innerEnd, end: innerEnd + tag.length + 3 };
}

function setInner(html, openRe, tag, value, from = 0) {
  const el = locate(html, openRe, tag, from);
  if (!el) throw new Error(`no element matching ${openRe} found`);
  return html.slice(0, el.innerStart) + value + html.slice(el.innerEnd);
}

function replaceElement(html, openRe, tag, value) {
  const el = locate(html, openRe, tag);
  if (!el) throw new Error(`no element matching ${openRe} found`);
  return html.slice(0, el.start) + value + html.slice(el.end);
}

function replaceRegion(html, startMark, endMark, value) {
  const a = html.indexOf(startMark);
  const b = html.indexOf(endMark);
  if (a === -1 || b === -1) throw new Error(`region ${startMark}..${endMark} not found`);
  return html.slice(0, a) + value + html.slice(b + endMark.length);
}

// Applies `pairs` outside <pre> blocks, `codePairs` inside them, and reports
// which entries never matched so stale ones can be pruned.
function translateText(html, pairs, codePairs, used) {
  // Longest key first, so a short entry can never eat the prefix of a longer one
  // ("초기화" vs "초기화 x (2,3)") and strand the remainder untranslated.
  const byLength = (t) => [...t].sort((a, b) => b[0].length - a[0].length);
  pairs = byLength(pairs);
  codePairs = byLength(codePairs);
  const parts = html.split(/(<pre[\s\S]*?<\/pre>)/);
  return parts
    .map((part) => {
      const table = part.startsWith('<pre') ? codePairs : pairs;
      for (const [from, to] of table) {
        if (part.includes(from)) {
          used.add(from);
          part = part.replaceAll(from, to);
        }
      }
      return part;
    })
    .join('');
}

/* -------------------------------------------------------------- localization */

// The post title appears as the <h1> and as the first entry of the index nav.
// Both come from the locale's `heading`, so they cannot drift apart — and this
// runs for the source language too, not just translations.
function applyHeading(html, heading) {
  if (!heading) return html;
  html = setInner(html, /<h1>/, 'h1', escapeHtml(heading));
  return html.replace(
    /(<a href="#intro">)[^<]*(<\/a>)/,
    (m, open, close) => open + escapeHtml(heading) + close,
  );
}

// Carries the source markup's equations into a translated body. `{{formula}}`
// marks where each one goes; anything left over lands before the first hint.
function mergeFormulas(body, sourceInner, where) {
  const formulas = [...sourceInner.matchAll(/<p class="formula">[\s\S]*?<\/p>/g)].map((m) => m[0]);
  const slots = (body.match(/\{\{formula\}\}/g) || []).length;
  if (slots > formulas.length) {
    fail(`${where}: body has ${slots} {{formula}} slots but the source has ${formulas.length}`);
  }
  let i = 0;
  let out = body.replace(/\{\{formula\}\}/g, () => formulas[i++] ?? '');
  const rest = formulas.slice(i).join('');
  if (!rest) return out;
  const hint = out.indexOf('<p class="hint">');
  return hint === -1 ? out + rest : out.slice(0, hint) + rest + out.slice(hint);
}

function localizeSection(slice, id, copy) {
  const where = `topics.${id}`;
  slice = setInner(slice, /<h2>/, 'h2', escapeHtml(copy.title));
  slice = setInner(slice, /<p class="topic-lead">/, 'p', escapeHtml(copy.lead));

  const bodies = [copy.body, copy.extra].filter(Boolean);
  let from = 0;
  for (const [n, body] of bodies.entries()) {
    const el = locate(slice, /<div class="topic-text">/, 'div', from);
    if (!el) {
      fail(`${where}: expected at least ${bodies.length} .topic-text blocks, found ${n}`);
      break;
    }
    const merged = mergeFormulas(body, el.inner, `${where}${n ? `.extra` : ''}`);
    slice = slice.slice(0, el.innerStart) + merged + slice.slice(el.innerEnd);
    from = el.innerStart + merged.length;
  }
  return slice;
}

function localize(content, locale) {
  const sections = [...content.matchAll(/<section id="([a-z]+)" class="topic">/g)]
    .map((m) => ({ id: m[1], start: m.index }));

  // Structural drift between the markup and the overlay is a build error, not a
  // page that silently ships half-translated.
  const inMarkup = new Set(sections.map((s) => s.id));
  const topics = locale.topics ?? {};
  const inCopy = new Set(Object.keys(topics));
  for (const id of inMarkup) if (!inCopy.has(id)) fail(`${locale.lang}: no copy for section "${id}"`);
  for (const id of inCopy) if (!inMarkup.has(id)) fail(`${locale.lang}: copy for unknown section "${id}"`);

  let html = content;
  // Reverse order keeps the recorded offsets valid as slices change length.
  for (let i = sections.length - 1; i >= 0; i--) {
    const { id, start } = sections[i];
    const end = i + 1 < sections.length ? sections[i + 1].start : html.length;
    const copy = topics[id];
    if (!copy) continue;
    const withExtra = id === 'pytorch' && locale.pytorchExtra
      ? { ...copy, extra: locale.pytorchExtra }
      : copy;
    html = html.slice(0, start) + localizeSection(html.slice(start, end), id, withExtra) + html.slice(end);
  }

  if (locale.languageLink) html = replaceElement(html, /<a class="language-link"[^>]*>/, 'a', locale.languageLink);
  if (locale.intro) html = replaceRegion(html, '<!-- intro:start -->', '<!-- intro:end -->', locale.intro.trim());
  if (locale.footnote) html = setInner(html, /<p class="la-footnote">/, 'p', locale.footnote);

  // Index nav: relabel each link from the translated section titles.
  const nav = locate(html, /<nav class="la-index"[^>]*>/, 'nav');
  if (nav) {
    const relabelled = nav.inner.replace(
      /(<a href="#([a-z]+)">)[^<]*(<\/a>)/g,
      (m, open, id, close) => (topics[id] ? open + escapeHtml(topics[id].title) + close : m),
    );
    html = html.slice(0, nav.innerStart) + relabelled + html.slice(nav.innerEnd);
    if (locale.navLabel) {
      html = html.slice(0, nav.start) +
        html.slice(nav.start, nav.start + relabelled.length + 200)
          .replace(/aria-label="[^"]*"/, `aria-label="${escapeHtml(locale.navLabel)}"`) +
        html.slice(nav.start + relabelled.length + 200);
    }
  }

  const used = new Set();
  html = translateText(html, locale.ui ?? [], locale.codeComments ?? [], used);
  for (const [from] of [...(locale.ui ?? []), ...(locale.codeComments ?? [])]) {
    if (!used.has(from)) console.warn(`  note: ${locale.lang} translation never matched: "${from}"`);
  }
  return html;
}

/* --------------------------------------------------------------- post meta */

const MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
  'August', 'September', 'October', 'November', 'December'];

// Words per minute for Latin prose, characters per minute for CJK. Code blocks
// are skipped: people scan them rather than read them at prose speed.
function readingMinutes(html) {
  const text = html.replace(/<pre[\s\S]*?<\/pre>/g, ' ').replace(/<[^>]+>/g, ' ');
  const cjk = (text.match(/[\u3131-\uD79D\u4E00-\u9FFF]/g) ?? []).length;
  const words = (text.match(/[A-Za-z0-9][A-Za-z0-9'’-]*/g) ?? []).length;
  return Math.max(1, Math.round(words / 200 + cjk / 400));
}

// Rewrites <p class="la-meta"> into the standard byline. The date is read back
// out of the existing <time datetime>, so content.html stays its only source.
function applyMeta(html, locale) {
  const author = locale.author ?? 'Seungheon Doh';
  const el = locate(html, /<p class="la-meta">/, 'p');
  if (!el) return { html, author };
  const iso = el.inner.match(/datetime="([\d-]{10})"/)?.[1];
  if (!iso) return { html, author };
  const [y, m, d] = iso.split('-').map(Number);
  const minutes = readingMinutes(html);
  const line = [
    `Date: <time datetime="${iso}">${MONTHS[m - 1]} ${d}, ${y}</time>`,
    `Estimated Reading Time: ${minutes} min`,
    `Author: ${escapeHtml(author)}`,
  ].join('<span class="la-meta-sep">|</span>');
  return {
    html: html.slice(0, el.innerStart) + line + html.slice(el.innerEnd),
    iso, minutes, author,
  };
}

/* --------------------------------------------------------------------- build */

async function buildPost(dir, stats) {
  const src = path.join(dir, 'src');
  const rel = path.relative(ROOT, dir);
  const content = await readFile(path.join(src, 'content.html'), 'utf8');
  const shell = await readFile(path.join(src, 'shell.html'), 'utf8');

  const files = (await readdir(src)).filter((f) => f.endsWith('.mjs')).sort();
  const locales = [];
  for (const f of files) {
    const mod = await import(pathToFileURL(path.join(src, f)).href);
    locales.push(mod.default);
  }
  if (!locales.length) return fail(`${rel}: no locale modules in src/`);
  const sources = locales.filter((l) => l.source);
  if (sources.length !== 1) return fail(`${rel}: expected exactly one locale with source:true, got ${sources.length}`);

  const alternates = locales
    .map((l) => `  <link rel="alternate" hreflang="${l.lang}" href="./${l.output}">`)
    .join('\n');

  for (const locale of locales) {
    // Comments in content.html (section numbering, region markers) are authoring
    // aids; they do not ship.
    const stripComments = (s) =>
      s.replace(/^[ \t]*<!--[\s\S]*?-->[ \t]*\r?\n/gm, '').replace(/<!--[\s\S]*?-->/g, '');
    const meta = applyMeta(
      stripComments(applyHeading(locale.source ? content : localize(content, locale), locale.heading)),
      locale,
    );
    const body = meta.html;
    stats.set(locale.output, meta);
    const page = shell
      .replace('{{lang}}', locale.lang)
      .replace('{{title}}', escapeHtml(locale.title))
      .replace('{{description}}', escapeHtml(locale.description))
      .replace('{{alternates}}', alternates)
      .replace('{{content}}', body.replace(/\s+$/, ''))
      .replace('<!doctype html>', `<!doctype html>\n<!-- ${BANNER} -->`);

    // The bug this build exists to prevent: a page shipping untranslated copy.
    // A locale declares which characters must never survive into its output —
    // e.g. an English page built from Korean source forbids Hangul. It cannot be
    // inferred, since a Korean overlay on an English source contains Hangul by
    // design.
    if (locale.forbid) {
      const strays = [...new Set(page.match(new RegExp(locale.forbid, 'g')) ?? [])];
      if (strays.length) fail(`${rel}/${locale.output}: untranslated text: ${strays.slice(0, 8).join(', ')}${strays.length > 8 ? ' …' : ''}`);
    }

    await writeFile(path.join(dir, locale.output), page);
    console.log(`  ${rel}/${locale.output}  (${locale.lang}, ${(page.length / 1024).toFixed(1)} KB)`);
  }
}

const postsDir = path.join(ROOT, 'posts');
const posts = (await readdir(postsDir, { withFileTypes: true }))
  .filter((d) => d.isDirectory() && existsSync(path.join(postsDir, d.name, 'src', 'content.html')))
  .map((d) => path.join(postsDir, d.name));

if (!posts.length) console.log('No posts with a src/ folder — nothing to build.');

const bySlug = new Map();
for (const p of posts) {
  console.log(`Building ${path.relative(ROOT, p)}`);
  const stats = new Map();
  await buildPost(p, stats);
  bySlug.set(path.basename(p), stats);
}

// The index page shows the same byline as the post header, so the reading time
// is written back into posts.json rather than maintained by hand. Each entry
// takes the figure for the page its `url` actually points at.
const manifestPath = path.join(ROOT, 'posts.json');
if (existsSync(manifestPath) && bySlug.size) {
  const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
  let touched = 0;
  for (const entry of manifest) {
    const stats = bySlug.get(entry.slug);
    if (!stats) continue;
    const meta = stats.get(path.basename(entry.url ?? 'index.html')) ?? [...stats.values()][0];
    if (!meta?.minutes) continue;
    if (meta.iso && meta.iso !== entry.date) {
      fail(`posts.json: "${entry.slug}" is dated ${entry.date} but the post says ${meta.iso}`);
    }
    if (entry.readingMinutes !== meta.minutes || entry.author !== meta.author) touched++;
    entry.readingMinutes = meta.minutes;
    entry.author = meta.author;
  }
  if (touched) {
    await writeFile(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
    console.log(`\n  posts.json updated (${touched} entr${touched === 1 ? 'y' : 'ies'})`);
  }
}

if (problems.length) {
  console.error(`\n${problems.length} problem(s):`);
  for (const p of problems) console.error(`  ✗ ${p}`);
  process.exit(1);
}
console.log('\nOK');
